In [1]:
# Import Dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Create a reference the CSV file desired
csv_path1 = "raw_data/city_data.csv"
csv_path2 = "raw_data/ride_data.csv"

# Read the CSVs into a Pandas DataFrame
city_df = pd.read_csv(csv_path1)
city_df.head()

ride_df = pd.read_csv(csv_path2)
ride_df.head()

#create data frame to find avg fare and total rides per city
city_ride = ride_df.groupby("city")
avg_fare = city_ride['fare'].mean()
total_ride = city_ride['fare'].count()
ride_final = pd.DataFrame({'avg_fare':avg_fare,'total_rides':total_ride})

#create data frame to find driver count and city type for each city
city_driver= city_df.groupby("city")
total_drivers_df= city_driver['driver_count'].sum()
city_type= city_driver["type"].last()
city_summary_final = pd.DataFrame({'driver_count':total_drivers_df,'type':city_type})

#combine city and ride data frames into single table
final_city_summary = pd.merge(ride_final, city_summary_final, left_index=True,right_index=True, how="outer")
final_city_summary.head()

               avg_fare  total_rides  driver_count      type
city
Alvarezhaven  23.928710           31            21     Urban
Alyssaberg    20.609615           26            67     Urban
Anitamouth    37.315556            9            16  Suburban
Antoniomouth  23.625000           22            21     Urban
Aprilchester  21.981579           19            49     Urban

In [4]:
# Create a bubble plot which compares that showcases the relationship between the variables on the above table.
x_urban = final_city_summary.loc[final_city_summary["type"]=="Urban"]["total_rides"]
y_urban = final_city_summary.loc[final_city_summary["type"]=="Urban"]["avg_fare"]
s_urban = final_city_summary.loc[final_city_summary["type"]=="Urban"]["driver_count"]*10

x_suburban = final_city_summary.loc[final_city_summary["type"]=="Suburban"]["total_rides"]
y_suburban = final_city_summary.loc[final_city_summary["type"]=="Suburban"]["avg_fare"]
s_suburban = final_city_summary.loc[final_city_summary["type"]=="Suburban"]["driver_count"]*10

x_rural = final_city_summary.loc[final_city_summary["type"]=="Rural"]["total_rides"]
y_rural = final_city_summary.loc[final_city_summary["type"]=="Rural"]["avg_fare"]
s_rural = final_city_summary.loc[final_city_summary["type"]=="Rural"]["driver_count"]*10
#data_bubble = final_city_summary.plot(kind="scatter", x="total rides", y="avg fare", s="driver_count",title="Pyber Ride Sharing Data (2016)")

#data_bubble.set_xlabel("Total Number of Rides (Per City)")
#data_bubble.set_ylabel("Average Fares($)")
#plt.show()

KeyError: 'total rides'

In [4]:
#Pie Charts

#create data frame to find total fare and total rides per city
pie_city_ride = ride_df.groupby("city")
pie_total_fare = pie_city_ride['fare'].sum()
pie_total_ride = pie_city_ride['fare'].count()
pie_ride_final = pd.DataFrame({'total_fare':pie_total_fare,'total_rides':pie_total_ride})

#create data frame to find driver count and city type for each city
pie_city_driver= city_df.groupby("city")
pie_total_drivers_df= pie_city_driver['driver_count'].sum()
pie_city_type= pie_city_driver["type"].last()
pie_city_summary_final = pd.DataFrame({'driver_count':pie_total_drivers_df,'type':city_type})

#combine city and ride data frames into single table
pie_final_city_summary = pd.merge(pie_ride_final, pie_city_summary_final, left_index=True,right_index=True, how="outer")
pie_final_city_summary.set_index("type")
pie_final_city_summary.head()

              total_fare  total_rides  driver_count      type
city
Alvarezhaven      741.79           31            21     Urban
Alyssaberg        535.85           26            67     Urban
Anitamouth        335.84            9            16  Suburban
Antoniomouth      519.75           22            21     Urban
Aprilchester      417.65           19            49     Urban

In [36]:
#% of Total Fares by City Type
fare_df = pie_final_city_summary[["type","total_fare"]]
fare_df = fare_df.set_index("type")
fare_df = fare_df.groupby("type").agg('sum')
fare_df
#colors = ["gold", "lightskyblue", "lightcoral"]
#explode = (0.1, 0.2, 0)
#fare_pie = pie_fare_df.pie(total_fare, explode=explode, labels=type, colors=colors,autopct="%.0f%%", shadow=True, startangle=140)
#fare_pie = pie_fare_df.plot(kind="pie",y=type,title=("Total Fares by City Type"))
#plt.show()

          total_fare
type
Rural        4255.09
Suburban    19317.88
Urban       40078.34

In [37]:
#* % of Total Rides by City Type

rides_df = pie_final_city_summary[["type","total_rides"]]
rides_df = rides_df.set_index("type")
rides_df = rides_df.groupby("type").agg('sum')
rides_df

#colors = ["gold", "lightskyblue", "lightcoral"]
#explode = (0.1, 0.2, 0)
#fare_pie = pie_rides_df.pie(total_fare, explode=explode, labels="type", colors=colors,autopct="%.01f%%", shadow=True, startangle=140)
#fare_pie = pie_rides_df.plot(kind="pie",y=type,title=("Total Fares by City Type"))
#plt.show()

          total_rides
type
Rural             125
Suburban          625
Urban            1625

In [25]:
#* % of Total Drivers by City Type

driver_df = pie_final_city_summary[["type","driver_count"]]
driver_df = driver_df.set_index("type")
driver_df = driver_df.groupby("type").agg('sum')
driver_df
#urban_drivers = driver_df.loc[driver_df["type"]=="Urban"]["driver_count"].sum()
#rural_drivers = driver_df.loc[driver_df["type"]=="Rural"]["driver_count"].sum()
#suburban_drivers = driver_df.loc[driver_df["type"]=="Suburban"]["driver_count"].sum()
#print(urban_drivers)
#print(rural_drivers)
#print(suburban_drivers)
#colors = ["gold", "lightskyblue", "lightcoral"]
#explode = (0.1, 0.2, 0)
#driver_pie = plt.pie(total_fare, explode=explode, labels=type, colors=colors,autopct="%.1f%%", shadow=True, startangle=140)
#driver_pie = pie_driver_df.plot(kind="pie",y=type,title=("Total Fares by City Type"))
#plt.show()


#make variable for each city type for each metric

          driver_count
type
Rural              104
Suburban           638
Urban             2607